### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by mikest** [BrunoFenzl/svg-round-corners#21]
Can you add a license file? Is this MIT? Public Domain? Something else?

**Comment by BrunoFenzl** [comment]
Hey @mikest Thanks for raising this issue and sorry for not getting back earlier. MIT would be perfect. I thought I had the license in place but it seems I forgot it. Contributions are more than welcome!

**Comment by mikest** [comment]
Awesome! I have a contribution for handling open polygons. Currently, the algorithm will add an arc to the start and end of the path open as if it was closed. I'll watch for the license update and send you a PR :)

**Comment by BrunoFenzl** [comment]
Closed by #22
