### ISSUE TITLE
roundCorners() produces arc segments at the head and tail of open paths.

### ISSUE THREAD

**Issue by mikest** [BrunoFenzl/svg-round-corners#23]
For open polygons the library will add arcs to the start/end of a polygon. Library should detect open paths and exclude arcs from the head/tail.

![image](https://user-images.githubusercontent.com/742517/114581686-c73f9f00-9c34-11eb-91d9-a95f3ca72f40.png)

**Comment by mikest** [comment]
@BrunoFenzl assign this to me if you like. I'll prep a PR shortly.

**Comment by BrunoFenzl** [comment]
closed by #24

**Comment by BrunoFenzl** [comment]
@mikest I accidentally published your version as 0.1.2. I hope you don't mind ;)

**Comment by mikest** [comment]
thank you so much!
