### ISSUE TITLE
Remove lodash

### ISSUE THREAD

**Issue by odolbin-altexsoft** [BrunoFenzl/svg-round-corners#54]
https://github.com/BrunoFenzl/svg-round-corners/blob/9a895a09f25041b3fa238d407474949364345b45/tests/utils.spec.js#L18

Could be a lodash `cloneDeep` removed(not used) or at least replaced with https://developer.mozilla.org/en-US/docs/Web/API/structuredClone, so the lodash can be removed from deps ?

**Comment by BrunoFenzl** [comment]
Yes, this dependency sneaked in a while ago and I plan to remove it. I'll let you know once it is gone
