### ISSUE TITLE
Precision for markOverlapped

### ISSUE THREAD

**Issue by JohnGemstone** [BrunoFenzl/svg-round-corners#56]
It is common to use svgs as clipping paths for images, and to set `clipPathUnits` to `objectBoundingBox` which remaps anything within normalized space (0-1) to the boundary of the element.

https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/clipPathUnits

Because of this small normalized space, two points that would normally be seen as pixels apart, are now subpixels apart in svg land and get marked as overlapping by the `Math.round` function. 

https://github.com/BrunoFenzl/svg-round-corners/blob/master/lib/utils.js#L314

What probably could be done is to match the precision of the `roundValues` function by reusing the `round` argument

https://github.com/BrunoFenzl/svg-round-corners/assets/17420741/d39f42c0-4bd5-448d-bb84-13848bd375ae

Thanks for the great package!

**Comment by BrunoFenzl** [comment]
Thanks @JohnGemstone For the input and the video! That helps a lot. This is indeed a case I didn't think about. Your suggestions seems good, let me just think/test the possible side effects of it.

**Comment by JohnGemstone** [comment]
@BrunoFenzl hold your horses, I've found a simple workaround. 
Just use normal pixel space and scale down the paths using 'transform' like so:

```ts
<svg>
  <clipPath id="clip" clipPathUnits="objectBoundingBox" transform="scale(0.01)">
    <path d={roundedPath}></path>
  </clipPath>
</svg>;
```


https://github.com/BrunoFenzl/svg-round-corners/assets/17420741/9409dc59-18fb-4c95-99c0-4d6db9260d9d


I swear I tried this but I must have put the transform property on the svg tag instead..
My bad!
Thanks for the quick response too

**Comment by BrunoFenzl** [comment]
Thats cool! I'm glad you found a simple solution! And thanks for sharing :)
